name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci
      
      - name: Lint backend
        working-directory: backend
        run: npm run lint
      
      - name: Run backend tests
        working-directory: backend
        run: npm test
      
      - name: Build backend
        working-directory: backend
        run: npm run build

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint
      
      - name: Run frontend tests
        working-directory: frontend
        run: npm test
      
      - name: Build frontend
        working-directory: frontend
        run: npm run build

  all-tests-pass:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: always()
    
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.test-backend.result }}" != "success" ]] || [[ "${{ needs.test-frontend.result }}" != "success" ]]; then
            echo "❌ Tests failed"
            exit 1
          fi
          echo "✅ All tests passed"
